# Generated by Django 3.2.4 on 2021-06-06 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210606_1511'),
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offered_price', models.IntegerField()),
                ('bid_status', models.CharField(choices=[('A', 'accepted'), ('D', 'declined'), ('P', 'pending')], default='pending', max_length=900)),
                ('buyer', models.ForeignKey(max_length=900, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='accounts.profile')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.card')),
                ('seller', models.ForeignKey(max_length=900, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='accounts.profile')),
            ],
        ),
    ]
