# Generated by Django 3.2.4 on 2021-06-06 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210606_1511'),
        ('trading', '0002_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('L', 'list'), ('K', 'keep')], default='list', max_length=900),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='trading.card'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='seller',
            field=models.OneToOneField(max_length=900, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='accounts.profile'),
        ),
    ]
