# Generated by Django 3.2.4 on 2021-06-06 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_auto_20210606_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='status',
        ),
    ]
