# Generated by Django 3.2.4 on 2021-06-06 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_auto_20210606_2122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='user',
            new_name='owner',
        ),
    ]
