# Generated by Django 3.2.4 on 2021-06-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_rename_user_card_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('L', 'list'), ('K', 'keep')], default='list', max_length=900),
        ),
    ]
