# Generated by Django 3.2.4 on 2021-06-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_card_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='picture',
            field=models.ImageField(default='https://bit.ly/3uY7NAX', upload_to=''),
        ),
    ]
