# Generated by Django 3.2.4 on 2021-06-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_card_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='picture',
            field=models.URLField(default='https://bit.ly/3uY7NAX'),
        ),
    ]
