# Generated by Django 3.2.4 on 2021-06-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_auto_20210608_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='buyer_update',
            field=models.CharField(choices=[('r', 'Read'), ('n', 'Not read')], default='n', max_length=100),
        ),
    ]
