# Generated by Django 3.2.4 on 2021-06-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210606_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('h', 'Hulk'), ('t', 'Thor'), ('c', 'Captain America'), ('i', 'Iron Man')], default='t', max_length=100),
        ),
    ]
